# General Exit Codes
EXIT_CODE_UNKNOWN_ERROR = 3

EXIT_CODE_INVALID_CREDENTIALS = 200
EXIT_CODE_INVALID_INSTANCE = 201
EXIT_CODE_BAD_REQUEST = 202

# CLUSTER 
EXIT_CODE_CLUSTER_STATUS_RESTARTING = 205
EXIT_CODE_CLUSTER_STATUS_ERRORED = 206

# DBFS EXIT CODES
EXIT_CODE_DBFS = 210
EXIT_CODE_DBFS = 211
EXIT_CODE_DBFS = 212

