# General Exit Codes
EXIT_CODE_UNKNOWN_ERROR = 3

EXIT_CODE_INVALID_CREDENTIALS = 200
EXIT_CODE_INVALID_INSTANCE = 201
EXIT_CODE_INVALID_CLUSTER = 202
EXIT_CODE_BAD_REQUEST = 203

# CLUSTER
EXIT_CODE_TERMINATION_SUCCESSFULLY_STARTED = 0
EXIT_CODE_CLUSTER_STATUS_RUNNING = 0
EXIT_CODE_CLUSTER_STATUS_RESTARTING = 0
EXIT_CODE_CLUSTER_STATUS_TERMINATING = 205
EXIT_CODE_CLUSTER_STATUS_ERRORED = 206



EXIT_CODE_DBFS_INVALID_SOURCE = 212
